---
# install elasticsearch on Debian family OS's.

- name: add elasticsearch apt key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch"
  tags:
    - aspects_elasticsearch
    - aspects_elasticsearch_install
    - aspects_elasticsearch_install_apt

- name: add elasticsearch apt repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/{{ aspects_elasticsearch_major_version_number }}/debian stable main"
    update_cache="yes"
    state="present"
  tags:
    - aspects_elasticsearch
    - aspects_elasticsearch_install
    - aspects_elasticsearch_install_apt

- name: install elasticsearch with apt
  apt: pkg="elasticsearch" state="present"
  tags:
    - aspects_elasticsearch
    - aspects_elasticsearch_install
    - aspects_elasticsearch_install_apt