---
# file: roles/elasticsearch/handlers/main.yml
- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes

- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes

- name: stop elasticsearch
  service: name=elasticsearch state=stopped enabled=yes